Repository depromeet/9th_3team_ThreeMeals, pull requests merged in 2021-05, with the labels that each got.

#20 feat: create the burger action on Header
  package.json
  src/components/molecules/Header.tsx
  src/stories/molecules/Header.stories.tsx
  yarn.lock
Labels: feat

#25 feat: add the plugins & hooks rules for dependencies
  .eslintrc.js
  package.json
  src/components/molecules/Header.tsx
  src/stories/molecules/Header.stories.tsx
  yarn.lock
Labels: feat

#27 feat: create the IconOnImage Component for using on Profile
  src/assets/images/icon_20_camera.png
  src/components/atoms/IconOnImage.tsx
  src/constants/images.ts
  src/stories/atoms/IconOnImage.stories.tsx
Labels: feat

#24 feat: making components
  .storybook/preview.js
  next.config.js
  pages/_app.tsx
  pages/_document.tsx
  pages/index.tsx
  src/assets/images/img_quiz_bl.png
  src/assets/images/img_quiz_gr.png
  src/assets/images/img_quiz_or.png
  src/assets/images/img_quiz_rd.png
  src/assets/images/img_quiz_yr.png
  src/assets/svgs/icon_32_like.svg
  src/assets/svgs/icon_32_like_active.svg
  src/assets/svgs/icon_arrow_left_wh.svg
  src/components/atoms/NameLabel.tsx
  src/components/atoms/Tag.tsx
  src/components/molecules/QuizCardHeader.tsx
  src/constants/images.ts
  src/stories/atoms/NameLabel.stories.tsx
  src/stories/atoms/Tag.stories.tsx
  src/stories/molecules/QuizCardHeader.stories.tsx
  src/utils/GlobalStyle.ts
Labels: feat

#30 feat: create pages & templates for [Profile]
  .babelrc
  package.json
  pages/index.tsx
  pages/profile.tsx
  pages/profileEdit.tsx
  src/assets/images/icon_16_insta_wh.png
  src/assets/images/icon_24_close_green_wh.png
  src/assets/images/share_16.png
  src/components/atoms/IconOnImage.tsx
  src/components/atoms/NextButton.tsx
  src/components/atoms/Tag.tsx
  src/components/molecules/Header.tsx
  src/components/pages/ProfileEditPage.tsx
  src/components/pages/ProfilePage.tsx
  src/components/templates/ProfileEditTemplate.tsx
  src/components/templates/ProfileTemplate.tsx
  src/constants/images.ts
  src/utils/GlobalStyle.ts
  yarn.lock
Labels: feat

#33 feat: connect to api from graphql server
  pages/_app.tsx
  pages/auth.tsx
  pages/index.tsx
  pages/profile.tsx
  pages/queryCountries.graphql
  src/lib/queries/getQueries.ts
Labels: feat

#35 refactor: add the process for uploading image files
  src/components/molecules/Modal.tsx
  src/components/pages/ProfilePage.tsx
  src/components/templates/ProfileTemplate.tsx
  src/utils/GlobalStyle.ts
Labels: refactor

#38 feat: create the content page
  package.json
  pages/content.tsx
  pages/newSecretCard.tsx
  pages/othersContent.tsx
  src/assets/images/button_floating_save_active.png
  src/assets/images/button_floating_save_disabled.png
  src/assets/images/img_newq_1.png
  src/assets/images/img_tape_newq.png
  src/assets/images/rightButton.png
  src/assets/images/write.png
  src/components/atoms/Tag.tsx
  src/components/molecules/Header.tsx
  src/components/molecules/ProfileContent.tsx
  src/components/organisms/QuestionCard.tsx
  src/components/pages/ContentPage.tsx
  src/components/pages/NewSecretCardPage.tsx
  src/components/pages/OthersContentPage.tsx
  src/components/templates/ContentTemplate.tsx
  src/components/templates/NewSecretCardTemplate.tsx
  src/components/templates/OthersContentTemplate.tsx
  src/constants/images.ts
  src/stories/molecules/ProfileContent.stories.tsx
  src/stories/organisms/QuestionCard.stories.tsx
  src/stories/pages/ContentPage.stories.tsx
  src/stories/pages/NewSecretCardPage.stories.tsx
  src/stories/pages/OthersContentPage.stories.tsx
  src/stories/templates/ContentTemplate.stories.tsx
  src/stories/templates/NewSecretCardTemplate.stories.tsx
  src/stories/templates/OthersContentTemplate.stories.tsx
  src/utils/GlobalStyle.ts
  yarn.lock
Labels: feat

#45 refactor: fix the padding from figma styling
  src/components/molecules/HomeTextCard.tsx
Labels: refactor

#46 refactor: add the condition for dividing login status
  src/components/molecules/Header.tsx
Labels: refactor

#48 feat: create the notification with dummyData
  pages/notification.tsx
  src/assets/images/tape_notification.png
  src/components/molecules/AlarmContentField.tsx
  src/components/pages/ContentPage.tsx
  src/components/pages/NotificationPage.tsx
  src/components/pages/OthersContentPage.tsx
  src/components/templates/NotificationTemplate.tsx
  src/constants/images.ts
  src/stories/pages/NotificationPage.stories.tsx
  src/stories/templates/NotificationTemplate.stories.tsx
Labels: feat

#49 feat: create post children comment-molecule and add get children comments query
  pages/auth.tsx
  src/components/molecules/PostChildrenComment.tsx
  src/lib/queries/getQueries.ts
  src/stories/molecules/PostChildrenComment.stories.tsx
Labels: feat

#52 feat: add login logic with apolloClient
  pages/_app.tsx
  pages/auth.tsx
  pages/profile.tsx
  src/lib/apolloClient.ts
  src/lib/queries/getQueries.ts
  src/lib/queries/signInQueries.ts
Labels: feat

#54 feat: create the AnswerCard for using answer
  src/assets/images/icon_24_comment.png
  src/assets/images/icon_32_option.png
  src/assets/images/icon_32_share.png
  src/components/organisms/AnswerCard.tsx
  src/components/organisms/QuestionCard.tsx
  src/constants/images.ts
  src/stories/organisms/AnswerCard.stories.tsx
Labels: feat

#56 feat: create the postComment with parent & children
  src/components/molecules/PostChildrenComment.tsx
  src/components/molecules/PostComment.tsx
  src/stories/molecules/PostChildrenComment.stories.tsx
  src/stories/molecules/PostComment.stories.tsx
Labels: feat

#57 feat: create AnswerDetailPage with ContentTemplate
  pages/answerDetail.tsx
  src/assets/images/inputSend.png
  src/assets/images/write.png
  src/components/atoms/DefaultInput.tsx
  src/components/molecules/Modal.tsx
  src/components/molecules/PostComment.tsx
  src/components/organisms/AnswerCard.tsx
  src/components/organisms/QuestionCard.tsx
  src/components/pages/AnswerDetailPage.tsx
  src/components/pages/ContentPage.tsx
  src/components/pages/NewSecretCardPage.tsx
  src/components/templates/AnswerDetailTemplate.tsx
  src/components/templates/ContentTemplate.tsx
  src/components/templates/NewSecretCardTemplate.tsx
  src/components/templates/OthersContentTemplate.tsx
  src/constants/images.ts
  src/lib/queries/getQueries.ts
  src/stories/molecules/PostComment.stories.tsx
  src/stories/organisms/AnswerCard.stories.tsx
  src/stories/organisms/QuestionCard.stories.tsx
  src/stories/pages/AnswerDetailPage.stories.tsx
  src/stories/templates/AnswerDetailTemplate.stories.tsx
  src/stories/templates/ContentTemplate.stories.tsx
Labels: feat, refactor
