Repository depromeet/9th_3team_ThreeMeals, pull requests merged in 2021-08, with the labels that each got.

#125 refactor: remove the closeBtn related to my profile url
  src/components/templates/ProfileTemplate.tsx
Labels: layout

#124 fix: update the profile to remove provider property
  src/components/atoms/Button.tsx
  src/lib/queries/meQueries.ts
Labels: bug

#126 fix: add feature-showing askPost only with comments
  src/components/templates/ContentTemplate.tsx
Labels: feat

#127 fix: add feature-24hour counting only with answer-comment
  src/components/organisms/QuestionCard.tsx
Labels: feat

#128 fix: open children-comments simultaneously
  src/components/molecules/PostComment.tsx
Labels: bug

#130 refactor: fix the condition for showing content data exactly
  src/components/templates/ContentTemplate.tsx
Labels: bug

#129 refactor: apply the opacity on textarea according to figma
  src/components/organisms/WriteQACard.tsx
Labels: layout

#131 fix: remove the dependencies for preventing initial state to use makeVar
  src/components/pages/WritePostPage.tsx
  src/components/templates/NewSecretCardTemplate.tsx
Labels: bug

#133 refactor: show askPost only with postState "completed"
  src/components/templates/ContentTemplate.tsx
Labels: refactor

#134 refactor: match comment border color with card color
  src/components/molecules/PostComment.tsx
  src/components/templates/AnswerDetailTemplate.tsx
Labels: refactor

#135 refactor: show only host name on children comment
  src/components/molecules/PostComment.tsx
  src/components/templates/AnswerDetailTemplate.tsx
Labels: refactor

#132 refactor: feature of opening childrenComment
  src/components/molecules/PostComment.tsx
  src/lib/queries/getCommentsQueries.ts
Labels: bug

#142 fix: fix the layout about question card & match fromAccount
  src/assets/images/thumbnail.png
  src/components/molecules/PostComment.tsx
  src/components/organisms/QuestionCard.tsx
  src/components/templates/ContentTemplate.tsx
  src/constants/images.ts
  src/lib/queries/getPostQueries.ts
Labels: bug

#141 refactor: update the date format from designer request
  src/components/molecules/PostComment.tsx
  src/components/organisms/AnswerCard.tsx
  src/utils/TimeDiffCalc.ts
Labels: refactor

#147 refactor: update the empty layout related to ask content
  src/components/pages/ContentPage.tsx
  src/components/templates/ContentTemplate.tsx
  src/components/templates/OthersContentTemplate.tsx
Labels: layout
