Repository depromeet/9th_3team_ThreeMeals, pull requests merged in 2021-06, with the labels that each got.

#62 refactor: match the button function on Content & fix the layout
  src/components/atoms/Tag.tsx
  src/components/molecules/LabelCardHeader.tsx
  src/components/molecules/PostComment.tsx
  src/components/organisms/AnswerCard.tsx
  src/components/organisms/QuestionCard.tsx
  src/components/pages/AnswerDetailPage.tsx
  src/components/pages/ContentPage.tsx
  src/components/pages/NewSecretCardPage.tsx
  src/components/templates/AnswerDetailTemplate.tsx
  src/components/templates/ContentTemplate.tsx
  src/components/templates/NewSecretCardTemplate.tsx
  src/components/templates/OthersContentTemplate.tsx
  src/stories/molecules/LabelCardHeader.stories.tsx
  src/stories/molecules/PostComment.stories.tsx
Labels: feat, refactor

#67 refactor: add the props for clipboard on AnswerCard
  src/components/organisms/AnswerCard.tsx
  src/components/templates/ContentTemplate.tsx
Labels: feat, refactor

#61 feat: connect the module for coping text on Tag
  package.json
  src/components/atoms/Tag.tsx
  src/components/templates/ProfileTemplate.tsx
  src/stories/atoms/Tag.stories.tsx
  yarn.lock
Labels: feat

#72 refactor: connect writePost on otherContents
  src/components/pages/OthersContentPage.tsx
  src/components/templates/OthersContentTemplate.tsx
Labels: feat

#81 feat: connect to header from user account on Header
  pages/contactUs.tsx
  pages/content.tsx
  pages/notification.tsx
  src/components/molecules/Header.tsx
  src/components/pages/ContactUsPage.tsx
  src/components/pages/ContentPage.tsx
  src/components/pages/NotificationPage.tsx
  src/components/pages/OthersContentPage.tsx
  src/components/templates/ContactUsTemplate.tsx
  src/components/templates/ContentTemplate.tsx
  src/components/templates/NotificationTemplate.tsx
  src/components/templates/OthersContentTemplate.tsx
  src/lib/queries/meQueries.ts
Labels: feat

#90 feat: connect the contactUs API
  src/components/pages/ContactUsPage.tsx
  src/lib/queries/createContactQueries.ts
Labels: feat

#95 refactor: merge the renect code
  pages/auth.tsx
  src/components/molecules/QuizCard.tsx
  src/components/pages/AnswerDetailPage.tsx
  src/components/pages/ContentPage.tsx
  src/components/templates/ContentTemplate.tsx
  src/components/templates/NewSecretCardTemplate.tsx
Labels: refactor

#97 refactor: add props on otherContents for showing timeStatus
  src/components/templates/OthersContentTemplate.tsx
Labels: refactor

#100 feat: connect the notification api from server & redesign
  src/assets/images/backgroundSticker.png
  src/components/molecules/AlarmContentField.tsx
  src/components/pages/NotificationPage.tsx
  src/components/templates/NotificationTemplate.tsx
  src/constants/images.ts
  src/lib/queries/getQueries.ts
  src/stories/molecules/AlarmContentField.stories.tsx
Labels: feat

#101 refactor: add the empty condition on ContentPage
  src/assets/images/img_tape_empty.png
  src/components/templates/ContentTemplate.tsx
  src/constants/images.ts
Labels: feat

#103 feat: connect the notification count api for showing noti
  src/assets/images/icon_24_alram_wh.png
  src/components/pages/ContentPage.tsx
  src/components/pages/OthersContentPage.tsx
  src/components/templates/ContentTemplate.tsx
  src/components/templates/NotificationTemplate.tsx
  src/components/templates/OthersContentTemplate.tsx
  src/constants/images.ts
  src/lib/queries/getQueries.ts
Labels: feat

#107 refactor: add the filter condition for seperating comments on AnswerNewOx
  src/components/pages/AnswerNewOXPage.tsx
Labels: refactor

#109 feat:connect the like api on Post cases
  src/assets/images/icon_32_like_active.png
  src/components/molecules/PostedSticker.tsx
  src/components/molecules/QuizCardHeader.tsx
  src/components/organisms/QuestionCard.tsx
  src/components/organisms/QuizAnswerCard.tsx
  src/components/pages/ContentPage.tsx
  src/components/templates/ContentTemplate.tsx
  src/lib/queries/createQueries.ts
  src/lib/queries/deleteQueries.ts
  src/lib/queries/getPostQueries.ts
  src/stories/templates/ContentTemplate.stories.tsx
Labels: feat

#113 refactor: card
  src/components/organisms/QuestionCard.tsx
  src/components/organisms/StickersList.tsx
  src/components/organisms/WriteQACard.tsx
  src/components/templates/OthersContentTemplate.tsx
Labels: refactor
